# Generated by Django 4.1.2 on 2023-11-07 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0002_hotelcontacts_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='photo',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel_info.roomtype'),
            preserve_default=False,
        ),
    ]
