# Generated by Django 4.1.2 on 2023-11-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0004_alter_room_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='start_cost',
            new_name='cost',
        ),
    ]
